Idle manager with separated logic
pypeclub/pype pull request #1147
Opened 2021-03-17 13:53 UTC by iLLiCiTiT

## Changes
- logic of idle manager was separated to separate file
   - the logic and python module `pynput` is imported only when needed
- renamed file `idle_manager.py` to `idle_module.py`

2021-03-18 16:21 UTC, mkolar approved these changes

2021-03-18 16:43 UTC, mkolar commented
Timer turns off fine, but no pop up shows. I smell something fishy in here ;)

2021-03-18 16:44 UTC, mkolar requested changes
Timer turns off fine, but no pop up shows. I smell something fishy in here ;)

2021-03-18 17:12 UTC, iLLiCiTiT commented
> I smell something fishy in here ;)

Me either. Issue was that it didn't expect multiple callbacks at the same time which may happen only if message time is really small. Fixed...

2021-03-22 08:39 UTC, mkolar approved these changes

2021-03-22 08:39 UTC, merged