Delete old versions
pypeclub/pype pull request #445
Opened 2020-08-17 14:10 UTC by tokejepsen

Unfortunately the nature of Loaders is that they operate on one representation at a time, so when multiple subsets are selected the settings dialog opens multiple times.
This could be solved with Loader options.

I was also thinking of splitting out the calculate to a different Loader, so better separate destructive actions.

2020-08-17 14:11 UTC, tokejepsen commented
Resolves https://github.com/pypeclub/pype/issues/396

2020-08-17 14:11 UTC, tokejepsen commented on pype/plugins/global/load/delete_old_versions.py
> +    def main(self, context):
I agree :)

2020-09-15 07:38 UTC, mkolar commented
This is crashing with our latest avalon core, but that is a bug in the core itself. @iLLiCiTiT could you please have a look?

2020-09-15 07:54 UTC, tokejepsen commented
@mkolar the fix is here; https://github.com/pypeclub/avalon-core/pull/176

2020-09-16 15:01 UTC, mkolar commented
Ah yeah. Sorry my bad

2020-09-16 15:59 UTC, mkolar requested changes
It's working pretty well for a first iteration of the action. there are a few caveats. Currently it only prints the calculated filesize if the debug mode is on, because it only prints to console. Secondly after deleting the library loader crashes when clicked :). @iLLiCiTiT will be able to advise about that.

2020-09-16 16:08 UTC, iLLiCiTiT commented
> Secondly after deleting the library loader crashes when clicked :)

I think the easiest would be to trigger `app.refresh()` when delete part is done.

But I'm not sure if that will trigger refresh of subsets widget. If not then must be executed `app.data["widgets"]["subsets"].model.refresh()`.

2020-09-17 07:09 UTC, tokejepsen commented
> I think the easiest would be to trigger app.refresh() when delete part is done.

Cool, I can have a look at that later.

@iLLiCiTiT any thoughts on implementing Loader settings into the Library Loader?

2020-09-17 08:16 UTC, iLLiCiTiT commented
> @iLLiCiTiT any thoughts on implementing Loader settings into the Library Loader?

I thought they are there? Created PR https://github.com/pypeclub/avalon-core/pull/192

2020-09-22 08:52 UTC, mkolar commented
Loader options in library are now merged to 2.x/develop

2020-09-22 08:55 UTC, tokejepsen commented
> Loader options in library are now merged to 2.x/develop

Thanks. Added an item to check on the description.

2021-01-30 19:59 UTC, tokejepsen commented
There is currently an issue when you run this on multiple assets, where the size is calculated per asset rather than a total of all the assets. This is because the Loader action is run per asset rather than on all the assets.

Guessing this is a design implementation of the Loader we'll have to live with?

2021-02-11 11:40 UTC, mkolar commented
>Guessing this is a design implementation of the Loader we'll have to live with?

I'm afraid so, at least for now. But I'm trying it out and it's looking good.

2021-02-11 11:55 UTC, tokejepsen commented
> Guessing this is a design implementation of the Loader we'll have to live with?

I was thinking whether there was a Loader class or modify the existing Loader class , so the Loader gets passed a list of assets instead of a single one?

2021-02-11 12:16 UTC, mkolar requested changes

2021-02-11 12:16 UTC, mkolar commented on pype/plugins/global/load/delete_old_versions.py
> +        qargparse.Boolean("publish", help="Remove publish folder:")
To keep this clear to the user I'd change the attribute names to nicer `versions to keep` and `delete folder`. I know the behaviour and caught myself mistaking whether it's version to keep or delete multiple time during testing.

2021-02-11 12:18 UTC, mkolar commented
> Actually since the context is being passed to the Loader, the context just needs another key assets for a list. But that the Loader logic would run it multiple times..

this kind of ties to the fact, that you see it on multiple representations, but it's really a version level action, so it's confusing. Maybe it could be fixed at the same time. @iLLiCiTiT what do you think?

![image](https://user-images.githubusercontent.com/3333008/107635535-98746f00-6c6b-11eb-97fd-e7fc957c5d1f.png)

2021-02-12 12:11 UTC, mkolar commented
Happy to merge to an intermediate branch, for some final touches on our end.

2021-02-12 12:11 UTC, merged

2021-02-12 12:47 UTC, tokejepsen commented
Up to you guys. I'm happy to keep this PR open until we have something that is more production ready, ei. not having pops up per asset.