Maya: Tiled EXRs to scanline EXRs render option
pypeclub/pype pull request #512
Opened 2020-09-08 17:20 UTC by antirotor

## Feature

Added new option to Maya **render** instance `Convert to scanline`. When checked, it will convert produced tiled EXRs to scanline EXRs as new representation. Useful when tiled renders are required because of heavy scene but compositing apps are having problems with it or are slow reading tiled EXRs.

EXRs are converted during publishing phase.

**Requires OpenImage IO**

⚠️ **Requires:** `PYPE_OIIO_PATH` environment variable pointing to **oiiotool** binary
|---|

2020-09-22 09:36 UTC, mkolar commented
This is a bit strange rigth now. It keeps both representations in DB `exr` and `exr_scanline` but they both point to the same file. 

I think we could keep just `exr` to prevent complications. we're not putting compression name into the repre name either.

2020-09-22 10:52 UTC, mkolar requested changes
see the comment about the representations

2020-09-22 11:58 UTC, antirotor commented
I think this is because integrator integrates both representations under same name - and that is problem by its own, isn't it? It differentiate only on representation extension key `{representation}`. But I think it is completely ok to want to have multiple types of the same image format in representations. So:

```javascript
[
    {
        "name": "exr_scanline",
        "ext": "exr"
    }, {
        "name": "exr_tiled",
        "ext": "exr"
    }
]
```
When this happens I guess last representation with same `ext` wins.

2020-09-24 07:46 UTC, mkolar commented
That depends on a publishing template. We have the optional `<output>` key which some extractors use for differentiating between various representations. Part of the problem is the discrepancy between anatomy `representation` and `extension` in the representation data. These should be the same and <output> in anatomy should be optionally mapped to `representation["name"]`

at this moment. the best would be to approach this the same way as quicktimes from extract review, by adding `output` key to the representation data so it get's picked up by the integrator.

2020-10-01 14:23 UTC, antirotor commented
This will now move files to temporary names and convert to original names with OIIO. No new representation. Same files (almost as they are tiled 👉 scanline converted) at the same place.

2020-10-01 17:08 UTC, mkolar commented
I'm still getting the `scanline` in the file names 
![image](https://user-images.githubusercontent.com/3333008/94840807-5152b380-0419-11eb-8d2e-00b33340e649.png)

it needs to be popped from `representation['output']` key

2020-10-06 16:13 UTC, merged