Intent value setting in pyblish pype
pypeclub/pype pull request #562
Opened 2020-09-24 14:28 UTC by iLLiCiTiT

## Issue
- intent value is not set to context until Intent combobox change index of selected item
- burnin use intent label even if intent value is not valid

## Changes
- intent is set all the time on play and validate buttons click
- extract burnin checks in intent value is valid before setting intent label to burnins data

2020-10-01 18:38 UTC, mkolar commented
with this setting 
![image](https://user-images.githubusercontent.com/3333008/94849150-4271fe00-0425-11eb-8922-7267ac1dc743.png)
I'm getting this burning if I don't select intent.
![image](https://user-images.githubusercontent.com/3333008/94849205-59185500-0425-11eb-91be-aefca5b36c2d.png)

I reckon if the key is an empty string (so we can technically have empty default, with label acting as combo box title). I can of course do `-` as default key and empty string as the label, but an empty combo-box doesn't really give much of an indication to the artist.

2020-10-01 18:43 UTC, mkolar commented
Actually if I leave empty string as intent label. I get `N/A` in the burning that should just send empty string to the burnins.

2020-10-01 18:46 UTC, mkolar requested changes
the last thing considering we are already digging into it. There is currently no way to force an order onto the intent items. so if using empty item as default it actually pops to a second place.

2020-10-02 14:00 UTC, iLLiCiTiT commented
> Actually if I leave empty string as intent label. I get N/A in the burning that should just send empty string to the burnins.

This should be fixed now.

> There is currently no way to force an order onto the intent items. so if using empty item as default it actually pops to a second place.

True, not hard to implement and I can do that. But there's not an item in settings gui that can do that (at this time).
```javascript
// Expected data stored in settings
{
    "items": [
        {"": "Intent"},
        {"wip": "WIP"},
        {"test": "TEST"},
        {"final": "FINAL"}
    ],
    "default": ""
}
```

2020-10-05 16:10 UTC, merged