567 Nuke Publish Camera
pypeclub/pype pull request #575
Opened 2020-09-30 08:33 UTC by jezscha

- PR #566  already merged into the branch for testing purposes
- publishing internal camera node with baked animation from parent axis's. Baked on word coordinate matrix XYZ so it should be working well even with Maya.

closing #565

2020-10-01 18:09 UTC, mkolar requested changes
Publishing and loading is working fine with one strange effect. When loading animated ABC to nuke. it doesn't show animation, until I manually disable and enable reading from the file. then it catches on correctly. Can you please have a look at that?

Updating and removing needs to be added as well, before merging.

2020-10-01 18:11 UTC, mkolar commented on pype/plugins/nuke/load/load_camera_abc.py
> +        # camera_node["file"].setValue(file)
if these lines are not needed let's remove them.

2020-10-02 15:49 UTC, jezscha commented
> Publishing and loading is working fine with one strange effect. When loading animated ABC to nuke. it doesn't show animation, until I manually disable and enable reading from the file. then it catches on correctly. Can you please have a look at that?
@mkolar I believe it is some internal Nuke bug as this is happening to me to. Didn't find any trace of evidence anybode had noticed it within community. When I had programmatically hit Reload button it want work either, although it is working in gui - try it.  
Not sure what to do with this really, @tokejepsen any idea here?

2020-10-02 15:54 UTC, tokejepsen commented
Dont really know about this, but you could force the node to into the control panel if that fixes the issue.

2020-10-05 16:18 UTC, merged