611 Simplify Hiero tag workflow
pypeclub/pype pull request #648
Opened 2020-10-16 11:47 UTC by jezscha

- refactoring Tag workflow - removing json, adding pype tag for single taging
- adding functions to lib for plugin wide use
- Creator with gui and renamer for hierarchical data use
- Publishing plugins refactoring for single tag collection
- Collectors in publishing refactoring for pre-collecting faze of publisher

2020-10-26 20:56 UTC, mkolar commented
I would simplify a few bits even more in the GUI the amount of categories gets somewhat confusing. How about merging a few to get this for the hierarchy and rename section:
![image](https://user-images.githubusercontent.com/3333008/97222663-07b67800-17cf-11eb-9aa8-d3c0419ba767.png)

For the shot attributes I'd rename this way and add source resolution option to get rid of another tag
![image](https://user-images.githubusercontent.com/3333008/97227575-f9b82580-17d5-11eb-806c-38574ec7283a.png)

2020-10-26 21:05 UTC, mkolar requested changes
I tried to do the changes myself, but couldn't force the approach to order the items for me correctly. Maybe I've done something wrong, but it looks like the order attribute in the dictionary is not really affecting the order. 

I'm considering this a prototype GUI, so let's please just fix the basics and move on with the functionality.

2020-10-27 11:16 UTC, jezscha commented on pype/plugins/hiero/create/create_shot_clip.py
> +                "previewOn": {"value": True, "type": "QCheckBox",
I am not sure if it is not rather preview mov files rather then review workflow. This is for ftrack preview video clip.

2020-10-27 12:15 UTC, jezscha commented
> I would simplify a few bits even more in the GUI the amount of categories gets somewhat confusing. How about merging a few to get this for the hierarchy and rename section:
These sections were kept serparatelly as they are two different thing. Usually there could be case where renaming is not needed and we would rather use the build in renaming. Although the hierarchy will be used in all cases.

2020-11-09 22:03 UTC, mkolar commented
I can't get the renamer to work at all. The tags are created and the data seem to reflect everything correctly.

2020-11-11 17:50 UTC, mkolar commented
Collecting goes through correctly now. Metadata is correct.

When renaming using the tool, it only renames the first 2 clips correctly and all following then get the same name as clip number 2.

2020-11-19 08:38 UTC, mkolar commented
Very nice. Much much easier to use and set up shot. I've made a small tweak to default values, and this is ready for merging of the subsequent PRs into here. 
My changes:
removed episode from default
shortened the shot padding
changes sequence default to `sq01` from sc020` 
![image](https://user-images.githubusercontent.com/3333008/99641591-c2423f00-2a4a-11eb-9423-69da42f6345d.png)

2020-11-19 08:38 UTC, mkolar approved these changes

2021-01-22 09:22 UTC, mkolar commented
this pr was cleaned up and replicated in #907 so we can close this

2021-01-22 09:22 UTC, closed without merging