686 standalonepublisher editorial from image sequences
pypeclub/pype pull request #699
Opened 2020-11-10 10:46 UTC by jezscha

## FEATURE:
- ability to read data from input folder path `CollectEditorial.source_dir`
        - "source_dir" supporting anatomy template filling: "{project[name]}/inputs"
        - "source_dir" supporting absolute path: "C:\\path\to\dir"
        - "source_dir" supporting relative path: "..\..\path\to\dir" or ".\path\to\dir"
- collecting files or folders by defined subset names and its alternatives from `CollectInstances.subsets`
- if in a `subset.extensions` is allowed 'mp4' extension and the file is found then it is used as ftrack review video file
- if in folder with subset data is found single jpg with `thumb` in name, it is used as thumbnail for the version

## TESTING
For testing add following lines to `pype-config/presets\plugins\standalonepublisher\publish.json`:

```
"CollectEditorial": {
      "extensions": [".mov", ".exr", ".jpeg"],
      "source_dir": "./inputs"
    },
    "CollectInstances": {
      "subsets": {
            "plateOffline": {
                "family": "plate",
                "families": ["clip", "review", "ftrack"],
                "extensions": [".jpg"]
            },
            "plateReference": {
                "family": "plate",
                "families": ["clip"],
                "extensions": [".jpg"]
            },
            "plateMain": {
                "family": "plate",
                "families": ["clip"],
                "extensions": [".exr", ".mp4", ".jpg"]
            },
            "shotMain": {
                "family": "shot",
                "families": []
            }
      },
      "custom_start_frame": 10001,
      "timeline_frame_start": 90000
    },
    "CollectHierarchyInstance": {
      "shot_rename_template": "{project[code]}_{_sequence_}_{_shot_}",
      "shot_rename_search_patterns": {
        "_sequence_": "(\\d{4})(?=_\\d{4})",
        "_shot_": "(\\d{4})(?!_\\d{4})"
      },
      "shot_add_hierarchy": {
            "parents_path": "{project}/{folder}/{sequence}",
            "parents": {
                "project": "{project[name]}",
                "sequence": "{_sequence_}",
                "folder": "shots"
            }
      },
      "shot_add_tasks": ["animation_rig", "compositing_environ", "compositing_all", "Art"]
    }
```

testing data are available form: https://drive.google.com/file/d/1kN_5F7-HogFKcD1fMXSrM9p7Usy1VU2J/view?usp=sharing

2020-11-16 20:58 UTC, mkolar commented
We have a conflict that needs to be sorted. And I have a comment about the tasks. Could we define them simply with a dictionary? It would be a lot more flexible and actually simpler to work with.
```
{
"task_name": "task_type",
"animation_char": "Animation",
"smoke": "FX,
...
}
```

2020-11-16 20:59 UTC, mkolar requested changes
Could we define tasks simply with a dictionary? It would be a lot more flexible and actually simpler to work with.
```
{
"task_name": "task_type",
"animation_char": "Animation",
"smoke": "FX,
...
}
```

2020-11-17 19:20 UTC, jezscha commented
> Could we define tasks simply with a dictionary? It would be a lot more flexible and actually simpler to work with.
> 
> ```
> {
> "task_name": "task_type",
> "animation_char": "Animation",
> "smoke": "FX,
> ...
> }
> ```

yeah, lets do it ;)

2020-11-20 11:14 UTC, mkolar approved these changes

2020-11-20 11:14 UTC, merged