Bugfix: Supercritical fix for Pype
pypeclub/pype pull request #810
Opened 2020-12-11 13:54 UTC by antirotor

# ❗ ❗ ❗ WARNING: CRITICAL BUG DETECTED
## Merge NOW!

Pype 3 is lacking critical feature. Without it it can destroy world or delete all porn. This PR is fixing it.

2020-12-11 14:46 UTC, iLLiCiTiT commented
I agree :D That gave me new motivation to continue with Pype.

2020-12-11 14:58 UTC, mkolar commented on pype/lib/terminal_splash.py
> +        sleep(0.05)
For everyone's sake, let's make this 0.02 shall we?

2020-12-11 15:00 UTC, mkolar requested changes
![facepalm-font-friday](https://user-images.githubusercontent.com/3333008/101918663-e9170f80-3bc9-11eb-92ab-753d34c0ae32.jpg)

2020-12-14 17:11 UTC, antirotor commented
Big yet unfamiliar
Think bigger than the biggest bar
Think big, that's only half as large
Bigger, better, twice as hard
Outsized, extra large
Velocity very fast
Bigger than the closest star
Bigger than the motor car

Quick, quiet, confident
Comfortable, permanent
Undisputed every tense
Not a trace of what went left
More equal than the best
Unparalleled success
Everybody
Be impressed!

2020-12-15 17:10 UTC, mkolar approved these changes

2020-12-15 17:10 UTC, merged